package com.uhc.ubh.arithmatic.calculation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1 2016-07-20T16:14:44.490+05:30
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", name = "ArithmaticCalculationServicePort")
@XmlSeeAlso({ ObjectFactory.class })
public interface ArithmaticCalculationServicePort {

    @WebMethod(action = "http://arithmatic.ubh.uhc.com/calculation/sum")
    @RequestWrapper(localName = "sum", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.SumResponse")
    @WebResult(name = "out", targetNamespace = "")
    public int sum(@WebParam(name = "in0", targetNamespace = "") int in0,
            @WebParam(name = "in1", targetNamespace = "") int in1);

    @WebMethod(action = "http://arithmatic.ubh.uhc.com/calculation/division")
    @RequestWrapper(localName = "division", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.DivisionResponse")
    @WebResult(name = "out", targetNamespace = "")
    public int division(@WebParam(name = "in0", targetNamespace = "") int in0,
            @WebParam(name = "in1", targetNamespace = "") int in1);

    @WebMethod(action = "http://arithmatic.ubh.uhc.com/calculation/sub")
    @RequestWrapper(localName = "sub", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.SubResponse")
    @WebResult(name = "out", targetNamespace = "")
    public int sub(@WebParam(name = "in0", targetNamespace = "") int in0,
            @WebParam(name = "in1", targetNamespace = "") int in1);

    @WebMethod(action = "http://arithmatic.ubh.uhc.com/calculation/multiply")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.MultiplyResponse")
    @WebResult(name = "out", targetNamespace = "")
    public int multiply(@WebParam(name = "in0", targetNamespace = "") int in0,
            @WebParam(name = "in1", targetNamespace = "") int in1);
}
